
package processor

// generated by scripts/genprocs
func init() {
	inLabel[`checker:testlib`]=[]string{`checker`,`input`,`output`,`answer`}
	ouLabel[`checker:testlib`]=[]string{`xmlreport`,`stderr`,`judgerlog`}
	inLabel[`compiler:auto`]=[]string{`source`,`option`}
	ouLabel[`compiler:auto`]=[]string{`result`,`log`,`judgerlog`}
	inLabel[`compiler:testlib`]=[]string{`source`}
	ouLabel[`compiler:testlib`]=[]string{`result`,`log`,`judgerlog`}
	inLabel[`runner:auto`]=[]string{`executable`,`stdin`,`conf`}
	ouLabel[`runner:auto`]=[]string{`stdout`,`stderr`,`judgerlog`}
}
