name: Docker

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install neccessary commands (judger)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y auditd flex make gengetopt bison xxd strace
    - name: Install LLVM and Clang (judger)
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "13"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build Image
      run: ./build/build_image.sh
    - name: Log in to registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/super-yaoj/judgeserver:latest
